// LspTest.cc — tests for the tpp-lsp server through the full LSP protocol.
//
// All suites are parameterised on configure-time data:
//   TestCases.h   — kTppSuccessCases, kTppDiagnosticCases
//   LspTestSpec.h — kLspTokenCaseNames, kLspFoldingCaseNames, kLspDefinitionCaseNames
//                   (generated by CMake; actual JSON is loaded at runtime)
//
// Suites:
//   LspPreviewTest      — tpp/renderPreview matches expected_output.txt
//   LspDiagnosticsTest  — publishDiagnostics matches expected_diagnostics.json
//   LspTokenTest        — expected tokens are present at exact positions
//   LspFoldingTest      — folding ranges match exactly
//   LspDefinitionTest   — go-to-definition returns the expected location

#include "LspClient.h"
#include "TestUtils.h"
#include "LspTestSpec.h"
#include "LspDefinitions.h"

#include <gtest/gtest.h>
#include <tpp/Diagnostic.h>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <cstdlib>
#include <string>
#include <tuple>
#include <vector>

// ── Runtime LSP spec structs ──────────────────────────────────────────────────

struct LspExpectedToken { int line, character, length; std::string type; };

struct LspTokenSpec {
    std::string testCase;
    std::string file;
    std::vector<LspExpectedToken> expected;
};

struct LspFoldingSpec {
    std::string testCase;
    std::string file;
    std::vector<std::pair<int, int>> expected; // {startLine, endLine}
};

struct LspDefinitionSpec {
    std::string name;
    std::string testCase;
    std::string file;
    int line = 0, character = 0;
    std::optional<std::string> expected_file; // absent = expect no result
    int expected_line = -1, expected_character = -1;
};

static void PrintTo(const LspTokenSpec &s, std::ostream *os)
    { *os << s.testCase << "/" << s.file; }
static void PrintTo(const LspFoldingSpec &s, std::ostream *os)
    { *os << s.testCase << "/" << s.file; }
static void PrintTo(const LspDefinitionSpec &s, std::ostream *os)
    { *os << s.testCase << " '" << s.name << "'"; }

// ── Runtime LSP spec loaders ──────────────────────────────────────────────────

static nlohmann::json loadLspJson(const char *testCase)
{
    std::ifstream f(std::string("TestCases/") + testCase + "/lsp-test.json");
    return nlohmann::json::parse(f);
}

static std::vector<LspTokenSpec> GetLspTokenSpecs()
{
    std::vector<LspTokenSpec> v;
    for (const char* const* p = tpp_test::kLspTokenCaseNames; *p; ++p)
    {
        auto j = loadLspJson(*p);
        LspTokenSpec spec;
        spec.testCase = *p;
        spec.file     = j["semantic_tokens"]["file"];
        for (const auto &t : j["semantic_tokens"]["expected_tokens"])
            spec.expected.push_back({t["line"], t["character"], t["length"], t["type"]});
        v.push_back(std::move(spec));
    }
    return v;
}

static std::vector<LspFoldingSpec> GetLspFoldingSpecs()
{
    std::vector<LspFoldingSpec> v;
    for (const char* const* p = tpp_test::kLspFoldingCaseNames; *p; ++p)
    {
        auto j = loadLspJson(*p);
        LspFoldingSpec spec;
        spec.testCase = *p;
        spec.file     = j["folding_ranges"]["file"];
        for (const auto &r : j["folding_ranges"]["expected"])
            spec.expected.push_back({r["startLine"], r["endLine"]});
        v.push_back(std::move(spec));
    }
    return v;
}

static std::vector<LspDefinitionSpec> GetLspDefinitionSpecs()
{
    std::vector<LspDefinitionSpec> v;
    for (const char* const* p = tpp_test::kLspDefinitionCaseNames; *p; ++p)
    {
        auto j = loadLspJson(*p);
        for (const auto &d : j["go_to_definition"])
        {
            LspDefinitionSpec spec;
            spec.name      = d["name"];
            spec.testCase  = *p;
            spec.file      = d["file"];
            spec.line      = d["line"];
            spec.character = d["character"];
            if (d.contains("expected_file"))
                spec.expected_file = d["expected_file"].get<std::string>();
            if (d.contains("expected_line"))
                spec.expected_line = d["expected_line"];
            if (d.contains("expected_character"))
                spec.expected_character = d["expected_character"];
            v.push_back(std::move(spec));
        }
    }
    return v;
}

// ── Free helpers ─────────────────────────────────────────────────────────────

static std::string fileUri(const std::filesystem::path &p)
{
    return "file://" + std::filesystem::weakly_canonical(p).string();
}

static std::string readFileStr(const std::filesystem::path &p)
{
    std::ifstream f(p);
    return std::string(std::istreambuf_iterator<char>(f),
                       std::istreambuf_iterator<char>());
}

static void writeFileStr(const std::filesystem::path &p, const std::string &content)
{
    std::filesystem::create_directories(p.parent_path());
    std::ofstream out(p);
    out << content;
}

// Relative source URL ("testname/file.tpp") → absolute file:// URI.
static std::string srcUri(const std::string &relUrl)
{
    return fileUri(std::filesystem::weakly_canonical("TestCases/" + relUrl));
}

// ── Diagnostic comparison helpers ─────────────────────────────────────────────

// Collect publishDiagnostics notifications into a sorted DiagnosticLSPMessage
// list.  Empty per-file lists are omitted.
static std::vector<tpp::DiagnosticLSPMessage> lspDiagsFromNotifs(
    const std::vector<nlohmann::json> &notifs)
{
    std::map<std::string, std::vector<tpp::Diagnostic>> byUri;
    for (const auto &n : notifs)
    {
        if (n.value("method", "") != "textDocument/publishDiagnostics")
            continue;
        const auto &params = n["params"];
        std::string uri = params.value("uri", "");
        if (uri.empty())
            continue;
        for (const auto &d : params.value("diagnostics", nlohmann::json::array()))
            byUri[uri].push_back(d.get<tpp::Diagnostic>());
    }
    auto diagLess = [](const tpp::Diagnostic &a, const tpp::Diagnostic &b)
    {
        return std::tie(a.range.start.line, a.range.start.character, a.message) <
               std::tie(b.range.start.line, b.range.start.character, b.message);
    };
    std::vector<tpp::DiagnosticLSPMessage> result;
    for (auto &[uri, diags] : byUri)
    {
        if (diags.empty())
            continue;
        std::sort(diags.begin(), diags.end(), diagLess);
        result.push_back({uri, diags});
    }
    std::sort(result.begin(), result.end(),
              [](const auto &a, const auto &b)
              { return a.uri < b.uri; });
    return result;
}

// Normalize expected diagnostics: relative URIs → absolute file://, then sort.
static std::vector<tpp::DiagnosticLSPMessage> normalizeExpected(
    std::vector<tpp::DiagnosticLSPMessage> diags)
{
    auto diagLess = [](const tpp::Diagnostic &a, const tpp::Diagnostic &b)
    {
        return std::tie(a.range.start.line, a.range.start.character, a.message) <
               std::tie(b.range.start.line, b.range.start.character, b.message);
    };
    for (auto &msg : diags)
    {
        msg.uri = srcUri(msg.uri);
        std::sort(msg.diagnostics.begin(), msg.diagnostics.end(), diagLess);
    }
    std::sort(diags.begin(), diags.end(),
              [](const auto &a, const auto &b)
              { return a.uri < b.uri; });
    return diags;
}

// ── Base fixture ─────────────────────────────────────────────────────────────
// Owns the LspClient lifetime.  Each suite's SetUp() calls startClient() once
// the workspace root is known.  TearDown() shuts the server down automatically.

template <typename T>
class LspParamFixture : public ::testing::TestWithParam<T>
{
protected:
    std::unique_ptr<tpp_test::LspClient> client_;
    T spec_;
    std::filesystem::path tcDir;

    // Override to return the test case directory name from the param type.
    virtual std::string getTestCaseName() const = 0;
    virtual void additionalSetUp() {}

    void SetUp() final
    {
        namespace fs = std::filesystem;
        spec_ = this->GetParam();
        tcDir = fs::weakly_canonical(std::string("TestCases/") + getTestCaseName());
        client_ = std::make_unique<tpp_test::LspClient>(TPP_LSP_EXE);
        client_->initialize(fileUri(tcDir));
        additionalSetUp();
    }

    void TearDown() override
    {
        if (client_)
        {
            client_->shutdown();
            client_.reset();
        }
    }
};

class LspTestWithLoading : public LspParamFixture<tTestCase>
{
protected:
    tLoadedTestCase loaded_;

    // tTestCase uses .name, not .testCase
    std::string getTestCaseName() const override { return spec_.name; }

    void additionalSetUp() override
    {
        loaded_ = spec_.extract();
    }
};

// ── LspPreviewTest ────────────────────────────────────────────────────────────
// For each positive test case, verify that tpp/renderPreview returns the
// expected rendered output.

class LspPreviewTest : public LspTestWithLoading
{
};

TEST_P(LspPreviewTest, RenderMatchesExpected)
{
    namespace fs = std::filesystem;
    fs::path tcDir = fs::weakly_canonical("TestCases/" + loaded_.name);

    auto result = client_->request("tpp/renderPreview", {{"configPath", (tcDir / "tpp-config.json").string()},
                                                         {"previewIndex", 0}});

    ASSERT_FALSE(result.contains("error"))
        << "tpp/renderPreview error: " << result.value("error", "") << "\nTest: " << loaded_.name;
    EXPECT_EQ(result.value("output", ""), loaded_.expectedOutput)
        << "Test: " << loaded_.name;
}

INSTANTIATE_TEST_SUITE_P(LspTests, LspPreviewTest,
                         ::testing::ValuesIn(GetPositiveTestCases()),
                         [](const testing::TestParamInfo<LspPreviewTest::ParamType> &info)
                         { return info.param.name; });

// ── LspDiagnosticsTest ────────────────────────────────────────────────────────
// For each test case with compile-time diagnostics (kTppDiagnosticCases,
// injected at configure time), verify that publishDiagnostics matches
// expected_diagnostics.json.  No runtime skipping needed.

class LspDiagnosticsTest : public LspTestWithLoading
{
};

TEST_P(LspDiagnosticsTest, PublishDiagnostics)
{
    auto notifications = client_->didOpen(srcUri(loaded_.sources[0].url),
                                          loaded_.sources[0].content);
    auto actual = lspDiagsFromNotifs(notifications);
    auto expected = normalizeExpected(loaded_.expectedDiagnostics);
    EXPECT_EQ(actual, expected)
        << "Test: " << loaded_.name
        << "\nActual:   " << nlohmann::json(actual).dump(2)
        << "\nExpected: " << nlohmann::json(expected).dump(2);
}

INSTANTIATE_TEST_SUITE_P(LspTests, LspDiagnosticsTest,
                         ::testing::ValuesIn(GetDiagnosticTestCases()),
                         [](const testing::TestParamInfo<LspDiagnosticsTest::ParamType> &info)
                         { return info.param.name; });

TEST(LspWatchTest, PolicyChangesReloadProjectAndPublishPolicyDiagnostics)
{
    namespace fs = std::filesystem;

    fs::path tempDir = fs::temp_directory_path() / fs::path("tpp-lsp-policy-watch-XXXXXX");
    std::string tempTemplate = tempDir.string();
    std::vector<char> tempBuffer(tempTemplate.begin(), tempTemplate.end());
    tempBuffer.push_back('\0');
    char *createdDir = mkdtemp(tempBuffer.data());
    ASSERT_NE(createdDir, nullptr);
    tempDir = fs::path(createdDir);

    const fs::path configPath = tempDir / "tpp-config.json";
    const fs::path templatePath = tempDir / "template.tpp";
    const fs::path policyPath = tempDir / "policies" / "escape-html.policy.json";

    writeFileStr(configPath,
        "{\n"
        "    \"types\": [],\n"
        "    \"templates\": [\"template.tpp\"],\n"
        "    \"replacement-policies\": [\"policies/*.policy.json\"],\n"
        "    \"previews\": [{\"template\": \"main\", \"input\": {\"v\": \"<x>\"}}]\n"
        "}\n");
    writeFileStr(templatePath,
        "template main(v: string)\n"
        "@v | policy=\"escape-html\"@\n"
        "END\n");
    writeFileStr(policyPath, "{\"tag\":123}\n");

    tpp_test::LspClient client(TPP_LSP_EXE);
    client.initialize(fileUri(tempDir));

    auto openNotifications = client.didOpen(fileUri(templatePath), readFileStr(templatePath));
    auto actual = lspDiagsFromNotifs(openNotifications);

    const std::string templateUri = fileUri(templatePath);
    const std::string policyUri = fileUri(policyPath);

    auto byUri = [&](const std::vector<tpp::DiagnosticLSPMessage> &messages, const std::string &uri)
        -> const std::vector<tpp::Diagnostic>*
    {
        for (const auto &message : messages)
            if (message.uri == uri)
                return &message.diagnostics;
        return nullptr;
    };

    const auto *templateDiags = byUri(actual, templateUri);
    ASSERT_NE(templateDiags, nullptr);
    ASSERT_EQ(templateDiags->size(), 1u);
    EXPECT_NE((*templateDiags)[0].message.find("unknown policy 'escape-html'"), std::string::npos);

    const auto *policyDiags = byUri(actual, policyUri);
    ASSERT_NE(policyDiags, nullptr);
    ASSERT_EQ(policyDiags->size(), 1u);
    EXPECT_NE((*policyDiags)[0].message.find("missing required string field 'tag'"), std::string::npos);

    writeFileStr(policyPath,
        "{\n"
        "    \"tag\": \"escape-html\",\n"
        "    \"replacements\": [{\"find\": \"<\", \"replace\": \"&lt;\"}]\n"
        "}\n");

    auto changeNotifications = client.didChangeWatchedFiles(nlohmann::json::array({
        {
            {"uri", fileUri(policyPath)},
            {"type", 2}
        }
    }));
    auto changed = lspDiagsFromNotifs(changeNotifications);

    const auto *clearedTemplateDiags = byUri(changed, templateUri);
    EXPECT_EQ(clearedTemplateDiags, nullptr);

    const auto *clearedPolicyDiags = byUri(changed, policyUri);
    EXPECT_EQ(clearedPolicyDiags, nullptr);

    client.shutdown();
    std::error_code ec;
    fs::remove_all(tempDir, ec);
}

// ── LspTokenTest ─────────────────────────────────────────────────────────────
// Parameterised on LspTokenSpec (discovered from per-case lsp-test.json).
// Decodes the delta-encoded response and verifies each expected token is present
// at the exact absolute position with the right type.  Non-exhaustive: extra
// tokens produced by the server are ignored.

class LspTokenTest : public LspParamFixture<LspTokenSpec>
{
protected:
    std::string getTestCaseName() const override { return spec_.testCase; }
    std::string targetUri_;

    void additionalSetUp() override
    {
        targetUri_ = fileUri(tcDir / spec_.file);
        client_->didOpen(targetUri_, readFileStr(tcDir / spec_.file));
    }
};

TEST_P(LspTokenTest, ExpectedTokensPresent)
{
    auto result = client_->request("textDocument/semanticTokens/full", {{"textDocument", {{"uri", targetUri_}}}});
    ASSERT_FALSE(result.contains("error"))
        << "semanticTokens/full error: " << result.value("error", "");
    ASSERT_TRUE(result.contains("data"))
        << "semanticTokens/full missing 'data' field";
    ASSERT_EQ(result["data"].size() % 5, 0u)
        << "Token data length must be a multiple of 5";

    const auto tokens = lsp::decodeTokens(result["data"]);

    for (const auto &exp : spec_.expected)
    {
        const auto expType = lsp::tokenTypeFromName(exp.type);
        const bool found   = std::any_of(
            tokens.begin(), tokens.end(),
            [&](const lsp::SemanticToken &tok)
            {
                return tok.line == exp.line && tok.character == exp.character
                    && tok.length == exp.length && tok.type == expType;
            });
        EXPECT_TRUE(found)
            << "Missing token: line=" << exp.line
            << " char=" << exp.character
            << " len=" << exp.length
            << " type=" << exp.type;
    }
}

INSTANTIATE_TEST_SUITE_P(LspTests, LspTokenTest,
                         ::testing::ValuesIn(GetLspTokenSpecs()),
                         [](const testing::TestParamInfo<LspTokenTest::ParamType> &info)
                         { return info.param.testCase; });

// ── LspFoldingTest ────────────────────────────────────────────────────────────
// Parameterised on LspFoldingSpec (discovered from per-case lsp-test.json).
// Verifies the exact set of folding ranges (order-independent by startLine).

class LspFoldingTest : public LspParamFixture<LspFoldingSpec>
{
protected:
    std::string getTestCaseName() const override { return spec_.testCase; }
    std::string targetUri_;

    void additionalSetUp() override
    {
        targetUri_ = fileUri(tcDir / spec_.file);
        client_->didOpen(targetUri_, readFileStr(tcDir / spec_.file));
    }
};

TEST_P(LspFoldingTest, ExactFoldingRanges)
{
    const auto &spec = GetParam();
    auto result = client_->request("textDocument/foldingRange", {{"textDocument", {{"uri", targetUri_}}}});
    ASSERT_FALSE(result.contains("error"))
        << "foldingRange error: " << result.value("error", "");
    ASSERT_TRUE(result.is_array())
        << "foldingRange response should be an array";
    ASSERT_EQ((int)result.size(), (int)spec.expected.size())
        << "Wrong number of folding ranges";

    // Sort by startLine for deterministic comparison.
    auto sorted = result;
    std::sort(sorted.begin(), sorted.end(),
              [](const nlohmann::json &a, const nlohmann::json &b)
              {
                  return a["startLine"].get<int>() < b["startLine"].get<int>();
              });
    for (int i = 0; i < (int)spec.expected.size(); ++i)
    {
        EXPECT_EQ(sorted[i]["startLine"].get<int>(), spec.expected[i].first)
            << "Range " << i << " startLine mismatch";
        EXPECT_EQ(sorted[i]["endLine"].get<int>(), spec.expected[i].second)
            << "Range " << i << " endLine mismatch";
    }
}

INSTANTIATE_TEST_SUITE_P(LspTests, LspFoldingTest,
                         ::testing::ValuesIn(GetLspFoldingSpecs()),
                         [](const testing::TestParamInfo<LspFoldingTest::ParamType> &info)
                         { return info.param.testCase; });

// ── LspDefinitionTest ─────────────────────────────────────────────────────────
// Parameterised on LspDefinitionSpec (discovered from per-case lsp-test.json).
// Opens all .tpp files in the test case, then verifies the definition target.

class LspDefinitionTest : public LspParamFixture<LspDefinitionSpec>
{
protected:
    std::string getTestCaseName() const override { return spec_.testCase; }
    void additionalSetUp() override
    {
        namespace fs = std::filesystem;
        for (const auto &entry : fs::directory_iterator(tcDir))
        {
            if (!entry.is_regular_file())
                continue;
            if (entry.path().extension() == ".tpp")
                client_->didOpen(fileUri(entry.path()), readFileStr(entry.path()));
        }
    }
};

TEST_P(LspDefinitionTest, TargetLocation)
{
    namespace fs = std::filesystem;
    std::string uri = fileUri(fs::weakly_canonical(
        std::string("TestCases/") + spec_.testCase + "/" + spec_.file));

    auto result = client_->request("textDocument/definition", {{"textDocument", {{"uri", uri}}},
                                                               {"position", {{"line", spec_.line}, {"character", spec_.character}}}});
    ASSERT_FALSE(result.contains("error"))
        << "definition error: " << result.value("error", "");

    if (!spec_.expected_file.has_value())
    {
        EXPECT_TRUE(result.is_null())
            << "Expected no definition but got: " << result.dump();
        return;
    }

    ASSERT_FALSE(result.is_null())
        << "Expected a definition location but got null";

    std::string exp_uri = fileUri(fs::weakly_canonical(
        std::string("TestCases/") + spec_.testCase + "/" + spec_.expected_file.value()));

    auto check = [&](const nlohmann::json &loc)
    {
        EXPECT_EQ(loc.value("uri", ""), exp_uri);
        if (spec_.expected_line >= 0) {
            EXPECT_EQ(loc["range"]["start"]["line"].get<int>(), spec_.expected_line);
        }
        if (spec_.expected_character >= 0) {
            EXPECT_EQ(loc["range"]["start"]["character"].get<int>(), spec_.expected_character);
        }
    };

    if (result.is_array())
    {
        ASSERT_FALSE(result.empty()) << "Expected at least one location";
        check(result[0]);
    }
    else
    {
        check(result);
    }
}

INSTANTIATE_TEST_SUITE_P(LspTests, LspDefinitionTest,
                         ::testing::ValuesIn(GetLspDefinitionSpecs()),
                         [](const testing::TestParamInfo<LspDefinitionTest::ParamType> &info)
                         { return info.param.name; });
